import { Achievement } from '../types';

export const ACHIEVEMENTS: Omit<Achievement, 'current' | 'completed' | 'claimed'>[] = [
  // 점수 업적
  {
    id: 'score_10k',
    name: '새내기',
    description: '10,000점 달성',
    category: 'score',
    target: 10000,
    reward: { gems: 10 },
    icon: '🌟',
  },
  {
    id: 'score_50k',
    name: '도전자',
    description: '50,000점 달성',
    category: 'score',
    target: 50000,
    reward: { gems: 25 },
    icon: '⭐',
  },
  {
    id: 'score_100k',
    name: '중수',
    description: '100,000점 달성',
    category: 'score',
    target: 100000,
    reward: { gems: 50 },
    icon: '🌟',
  },
  {
    id: 'score_500k',
    name: '고수',
    description: '500,000점 달성',
    category: 'score',
    target: 500000,
    reward: { gems: 100 },
    icon: '💫',
  },
  {
    id: 'score_1m',
    name: '달인',
    description: '1,000,000점 달성',
    category: 'score',
    target: 1000000,
    reward: { gems: 200, skin: 'score_master' },
    icon: '🏆',
  },
  {
    id: 'score_5m',
    name: '전설',
    description: '5,000,000점 달성',
    category: 'score',
    target: 5000000,
    reward: { gems: 500 },
    icon: '👑',
  },
  {
    id: 'score_10m',
    name: '신화',
    description: '10,000,000점 달성',
    category: 'score',
    target: 10000000,
    reward: { gems: 1000, skin: 'mythic_legend' },
    icon: '🔱',
  },

  // 콤보 업적
  {
    id: 'combo_10',
    name: '콤보 입문',
    description: '10 콤보 달성',
    category: 'combo',
    target: 10,
    reward: { gems: 10 },
    icon: '🔥',
  },
  {
    id: 'combo_20',
    name: '콤보 숙련',
    description: '20 콤보 달성',
    category: 'combo',
    target: 20,
    reward: { gems: 25 },
    icon: '🔥',
  },
  {
    id: 'combo_30',
    name: '콤보 마스터',
    description: '30 콤보 달성',
    category: 'combo',
    target: 30,
    reward: { gems: 50 },
    icon: '🔥',
  },
  {
    id: 'combo_50',
    name: '콤보 레전드',
    description: '50 콤보 달성',
    category: 'combo',
    target: 50,
    reward: { gems: 100, skin: 'combo_legend' },
    icon: '💥',
  },
  {
    id: 'combo_100',
    name: '콤보 신',
    description: '100 콤보 달성',
    category: 'combo',
    target: 100,
    reward: { gems: 300 },
    icon: '⚡',
  },

  // 연쇄 업적
  {
    id: 'chain_5',
    name: '연쇄 초보',
    description: '5연쇄 달성',
    category: 'chain',
    target: 5,
    reward: { gems: 15 },
    icon: '⛓️',
  },
  {
    id: 'chain_10',
    name: '연쇄 달인',
    description: '10연쇄 달성',
    category: 'chain',
    target: 10,
    reward: { gems: 50 },
    icon: '⛓️',
  },
  {
    id: 'chain_15',
    name: '연쇄 신',
    description: '15연쇄 달성',
    category: 'chain',
    target: 15,
    reward: { gems: 150, skin: 'chain_master' },
    icon: '🔗',
  },
  {
    id: 'chain_20',
    name: '연쇄 전설',
    description: '20연쇄 달성',
    category: 'chain',
    target: 20,
    reward: { gems: 300 },
    icon: '💎',
  },

  // 특수 업적
  {
    id: 'perfect_clear',
    name: '퍼펙트!',
    description: '보드 완전 클리어',
    category: 'special',
    target: 1,
    reward: { gems: 100 },
    icon: '✨',
  },
  {
    id: 'comeback',
    name: '역전의 명수',
    description: '위험 상황에서 탈출',
    category: 'special',
    target: 1,
    reward: { gems: 75 },
    icon: '🦸',
  },
  {
    id: 'speed_demon',
    name: '스피드 데몬',
    description: '1분 내 50,000점',
    category: 'special',
    target: 1,
    reward: { gems: 100 },
    icon: '🏎️',
  },
  {
    id: 'no_powerup',
    name: '순수주의자',
    description: '파워업 없이 레벨 20',
    category: 'special',
    target: 1,
    reward: { gems: 150 },
    icon: '🧘',
  },
  {
    id: 'all_colors',
    name: '무지개',
    description: '5가지 색 동시에 융합',
    category: 'special',
    target: 1,
    reward: { gems: 50 },
    icon: '🌈',
  },
  {
    id: 'first_blood',
    name: '시작이 반',
    description: '첫 게임 완료',
    category: 'special',
    target: 1,
    reward: { gems: 5 },
    icon: '🎉',
  },
  {
    id: 'marathon',
    name: '마라토너',
    description: '30분 연속 플레이',
    category: 'special',
    target: 1,
    reward: { gems: 80 },
    icon: '🏃',
  },

  // 플레이 업적
  {
    id: 'games_10',
    name: '입문자',
    description: '10게임 플레이',
    category: 'play',
    target: 10,
    reward: { coins: 500 },
    icon: '🎮',
  },
  {
    id: 'games_100',
    name: '단골',
    description: '100게임 플레이',
    category: 'play',
    target: 100,
    reward: { gems: 50 },
    icon: '🎮',
  },
  {
    id: 'games_500',
    name: '매니아',
    description: '500게임 플레이',
    category: 'play',
    target: 500,
    reward: { gems: 200 },
    icon: '🕹️',
  },
  {
    id: 'games_1000',
    name: '중독자',
    description: '1000게임 플레이',
    category: 'play',
    target: 1000,
    reward: { gems: 500 },
    icon: '🎰',
  },
  {
    id: 'time_1h',
    name: '시간가는줄',
    description: '총 1시간 플레이',
    category: 'play',
    target: 3600,
    reward: { coins: 1000 },
    icon: '⏰',
  },
  {
    id: 'time_10h',
    name: '덕후',
    description: '총 10시간 플레이',
    category: 'play',
    target: 36000,
    reward: { gems: 100 },
    icon: '⌛',
  },
  {
    id: 'time_100h',
    name: '크로마폴 인생',
    description: '총 100시간 플레이',
    category: 'play',
    target: 360000,
    reward: { gems: 1000, skin: 'veteran' },
    icon: '🎖️',
  },

  // 숨겨진 업적
  {
    id: 'secret_gravity',
    name: '???',
    description: '모든 중력 방향 사용',
    category: 'hidden',
    target: 1,
    reward: { gems: 50 },
    icon: '❓',
  },
  {
    id: 'secret_lucky',
    name: '???',
    description: '연속 3번 레어 획득',
    category: 'hidden',
    target: 1,
    reward: { gems: 100 },
    icon: '❓',
  },
  {
    id: 'secret_developer',
    name: '???',
    description: '개발자의 의도 발견',
    category: 'hidden',
    target: 1,
    reward: { gems: 200 },
    icon: '❓',
  },
];

// 업적 초기화 함수
export function initializeAchievements(): Achievement[] {
  return ACHIEVEMENTS.map(achievement => ({
    ...achievement,
    current: 0,
    completed: false,
    claimed: false,
  }));
}
